/* The following code was generated by JFlex 1.4.3 on 21/05/23, 15:44 */

import compilerTools.TextColor;
import java.awt.Color;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 21/05/23, 15:44 from the specification file
 * <tt>C:/Users/antho/OneDrive/Documentos/NetBeansProjects/AnalizadorLexico28/src/codigo/LexerColor.flex</tt>
 */
class LexerColor {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\25\1\65"+
    "\1\65\1\30\1\65\1\26\1\0\1\30\1\30\1\5\1\21\1\65"+
    "\1\22\1\65\1\4\1\17\11\20\1\65\1\30\1\23\1\24\1\23"+
    "\1\65\1\65\1\16\1\47\1\61\1\44\1\14\1\52\1\15\1\62"+
    "\1\34\2\6\1\50\1\6\1\35\1\45\2\6\1\56\1\55\1\36"+
    "\1\46\1\13\1\64\3\6\1\30\1\0\1\30\1\0\1\66\1\65"+
    "\1\12\1\42\1\57\1\37\1\10\1\51\1\11\1\60\1\31\2\6"+
    "\1\43\1\6\1\32\1\40\2\6\1\54\1\53\1\33\1\41\1\7"+
    "\1\63\3\6\1\30\1\27\1\30\1\65\42\0\1\65\12\0\1\65"+
    "\3\0\1\65\16\0\1\65\1\0\1\6\7\0\1\6\3\0\1\6"+
    "\3\0\1\6\1\0\1\6\6\0\1\6\1\0\1\6\4\0\1\6"+
    "\7\0\1\6\3\0\1\6\3\0\1\6\1\0\1\6\6\0\1\6"+
    "\1\0\1\6\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\36\3\1\1\1\3\1\4\1\0"+
    "\1\1\3\3\1\1\2\3\1\5\2\3\1\5\2\3"+
    "\1\5\15\3\2\4\2\0\2\3\1\6\20\3\1\0"+
    "\1\4\1\7\1\10\14\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\334\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba"+
    "\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b\0\u0672"+
    "\0\u06a9\0\u06e0\0\334\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3"+
    "\0\u082a\0\u0861\0\u0898\0\67\0\u08cf\0\u0113\0\u0906\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5"+
    "\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad"+
    "\0\u0ce4\0\u0d1b\0\67\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0113"+
    "\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf"+
    "\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167"+
    "\0\u119e\0\u0d52\0\u0113\0\u0113\0\u11d5\0\u120c\0\u1243\0\u127a"+
    "\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\3\7"+
    "\1\11\3\7\1\12\1\13\1\14\1\15\1\16\2\17"+
    "\1\20\1\21\1\6\1\22\1\7\1\23\1\24\2\7"+
    "\1\25\2\7\1\26\1\27\1\30\2\7\1\31\1\32"+
    "\1\33\1\34\1\35\1\7\1\36\1\7\1\37\1\7"+
    "\1\40\1\7\1\41\1\42\1\43\1\44\71\0\1\4"+
    "\70\0\1\45\1\46\11\47\12\0\34\47\1\0\1\47"+
    "\6\0\11\47\12\0\34\47\1\0\1\47\6\0\13\7"+
    "\10\0\34\7\1\0\1\7\6\0\2\7\1\50\3\7"+
    "\1\51\4\7\10\0\34\7\1\0\1\7\6\0\2\7"+
    "\1\50\3\7\1\52\4\7\10\0\34\7\1\0\1\7"+
    "\6\0\11\47\1\2\1\53\10\0\34\47\1\0\1\47"+
    "\6\0\11\47\2\13\10\0\34\47\1\0\1\47\6\0"+
    "\11\47\2\0\1\54\7\0\34\47\1\0\1\47\6\0"+
    "\11\47\3\0\1\54\6\0\34\47\1\0\1\47\24\0"+
    "\1\54\50\0\11\47\5\0\1\54\4\0\34\47\1\0"+
    "\1\47\6\0\11\47\7\0\1\54\2\0\34\47\1\0"+
    "\1\47\6\0\11\47\10\0\1\54\1\0\34\47\1\0"+
    "\1\47\6\0\13\7\10\0\1\7\1\55\16\7\1\56"+
    "\13\7\1\0\1\7\6\0\13\7\10\0\23\7\1\57"+
    "\10\7\1\0\1\7\6\0\13\7\10\0\1\7\1\55"+
    "\2\7\1\60\13\7\2\56\12\7\1\0\1\7\6\0"+
    "\13\7\10\0\7\7\1\61\24\7\1\0\1\7\6\0"+
    "\13\7\10\0\7\7\1\62\24\7\1\0\1\7\6\0"+
    "\13\7\10\0\7\7\1\63\24\7\1\0\1\7\6\0"+
    "\13\7\10\0\7\7\1\61\4\7\1\64\17\7\1\0"+
    "\1\7\6\0\13\7\10\0\7\7\1\62\4\7\1\65"+
    "\17\7\1\0\1\7\6\0\13\7\10\0\7\7\1\63"+
    "\4\7\1\66\17\7\1\0\1\7\6\0\4\7\1\67"+
    "\6\7\10\0\7\7\1\70\2\7\1\71\21\7\1\0"+
    "\1\7\6\0\13\7\10\0\7\7\1\70\2\7\1\71"+
    "\1\7\1\72\2\7\1\73\14\7\1\0\1\7\6\0"+
    "\13\7\10\0\2\7\1\74\31\7\1\0\1\7\6\0"+
    "\13\7\10\0\2\7\1\74\2\7\1\75\26\7\1\0"+
    "\1\7\6\0\13\7\10\0\27\7\1\76\4\7\1\0"+
    "\1\7\6\0\13\7\10\0\27\7\1\76\1\7\1\77"+
    "\2\7\1\0\1\7\6\0\13\7\10\0\27\7\1\100"+
    "\4\7\1\0\1\7\6\0\13\7\10\0\27\7\1\100"+
    "\1\7\1\101\2\7\1\0\1\7\6\0\11\47\2\7"+
    "\10\0\34\47\1\0\1\47\1\45\1\102\1\103\64\45"+
    "\5\104\1\105\61\104\6\0\13\47\10\0\34\47\1\0"+
    "\1\47\6\0\3\7\1\106\3\7\1\107\3\7\10\0"+
    "\34\7\1\0\1\7\6\0\7\7\1\106\3\7\10\0"+
    "\34\7\1\0\1\7\6\0\3\7\1\106\3\7\1\106"+
    "\3\7\10\0\34\7\1\0\1\7\17\0\2\53\54\0"+
    "\13\7\10\0\2\7\1\110\31\7\1\0\1\7\6\0"+
    "\13\7\10\0\10\7\1\111\23\7\1\0\1\7\6\0"+
    "\13\7\10\0\5\7\1\110\26\7\1\0\1\7\6\0"+
    "\13\7\10\0\10\7\1\112\23\7\1\0\1\7\6\0"+
    "\13\7\10\0\7\7\1\113\24\7\1\0\1\7\6\0"+
    "\13\7\10\0\1\7\1\114\32\7\1\0\1\7\6\0"+
    "\13\7\10\0\15\7\1\115\16\7\1\0\1\7\6\0"+
    "\13\7\10\0\14\7\1\116\17\7\1\0\1\7\6\0"+
    "\13\7\10\0\4\7\1\117\27\7\1\0\1\7\6\0"+
    "\13\7\10\0\12\7\1\120\21\7\1\0\1\7\6\0"+
    "\13\7\10\0\23\7\1\56\10\7\1\0\1\7\6\0"+
    "\13\7\10\0\7\7\1\121\24\7\1\0\1\7\6\0"+
    "\13\7\10\0\25\7\1\56\6\7\1\0\1\7\6\0"+
    "\13\7\10\0\14\7\1\122\17\7\1\0\1\7\6\0"+
    "\13\7\10\0\23\7\1\123\10\7\1\0\1\7\6\0"+
    "\13\7\10\0\25\7\1\124\6\7\1\0\1\7\6\0"+
    "\4\7\1\125\6\7\10\0\34\7\1\0\1\7\6\0"+
    "\10\7\1\126\2\7\10\0\34\7\1\0\1\7\6\0"+
    "\13\7\10\0\1\127\33\7\1\0\1\7\6\0\13\7"+
    "\10\0\3\7\1\130\30\7\1\0\1\7\2\0\1\103"+
    "\64\0\5\104\1\131\65\104\1\132\1\131\61\104\6\0"+
    "\4\7\1\133\3\7\1\133\2\7\10\0\34\7\1\0"+
    "\1\7\6\0\10\7\1\133\2\7\10\0\34\7\1\0"+
    "\1\7\6\0\2\7\1\134\10\7\10\0\34\7\1\0"+
    "\1\7\6\0\13\7\10\0\11\7\1\135\22\7\1\0"+
    "\1\7\6\0\13\7\10\0\12\7\1\136\21\7\1\0"+
    "\1\7\6\0\3\7\1\110\7\7\10\0\34\7\1\0"+
    "\1\7\6\0\13\7\10\0\16\7\1\137\15\7\1\0"+
    "\1\7\6\0\13\7\10\0\17\7\1\140\14\7\1\0"+
    "\1\7\6\0\7\7\1\110\3\7\10\0\34\7\1\0"+
    "\1\7\6\0\13\7\10\0\22\7\1\111\11\7\1\0"+
    "\1\7\6\0\4\7\1\55\6\7\10\0\34\7\1\0"+
    "\1\7\6\0\10\7\1\60\2\7\10\0\34\7\1\0"+
    "\1\7\6\0\13\7\10\0\1\63\33\7\1\0\1\7"+
    "\6\0\13\7\10\0\3\7\1\66\30\7\1\0\1\7"+
    "\6\0\13\7\10\0\23\7\1\110\10\7\1\0\1\7"+
    "\6\0\13\7\10\0\25\7\1\110\6\7\1\0\1\7"+
    "\6\0\13\7\10\0\12\7\1\141\21\7\1\0\1\7"+
    "\6\0\13\7\10\0\17\7\1\142\14\7\1\0\1\7"+
    "\4\104\1\103\1\131\61\104\6\0\13\7\10\0\12\7"+
    "\1\143\21\7\1\0\1\7\6\0\2\7\1\144\10\7"+
    "\10\0\34\7\1\0\1\7\6\0\13\7\10\0\17\7"+
    "\1\145\14\7\1\0\1\7\6\0\6\7\1\146\4\7"+
    "\10\0\34\7\1\0\1\7\6\0\2\7\1\56\10\7"+
    "\10\0\34\7\1\0\1\7\6\0\6\7\1\56\4\7"+
    "\10\0\34\7\1\0\1\7\6\0\2\7\1\110\10\7"+
    "\10\0\34\7\1\0\1\7\6\0\4\7\1\147\6\7"+
    "\10\0\34\7\1\0\1\7\6\0\6\7\1\110\4\7"+
    "\10\0\34\7\1\0\1\7\6\0\10\7\1\150\2\7"+
    "\10\0\34\7\1\0\1\7\6\0\13\7\10\0\1\7"+
    "\1\110\32\7\1\0\1\7\6\0\13\7\10\0\4\7"+
    "\1\110\27\7\1\0\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5225];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\41\1\1\0\5\1\1\11"+
    "\26\1\1\11\2\0\23\1\1\0\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private TextColor textColor(long start, int size, Color color){
        return new TextColor((int) start, size, color);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerColor(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerColor(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 246) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public TextColor yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 7: 
          { return textColor(yychar, yylength(), new Color(0, 255, 255));
          }
        case 9: break;
        case 2: 
          { /*Ignorar*/
          }
        case 10: break;
        case 8: 
          { return textColor(yychar, yylength(), new Color(50, 200, 50));
          }
        case 11: break;
        case 3: 
          { return textColor(yychar, yylength(), new Color(0, 0, 0));
          }
        case 12: break;
        case 6: 
          { return textColor(yychar, yylength(), new Color(0, 200, 0));
          }
        case 13: break;
        case 1: 
          { return textColor(yychar, yylength(), new Color(255, 0, 0));
          }
        case 14: break;
        case 4: 
          { return textColor(yychar, yylength(), new Color(146, 146, 146));
          }
        case 15: break;
        case 5: 
          { return textColor(yychar, yylength(), new Color(0, 0, 200));
          }
        case 16: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
